name: Deploy to Server

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      STREAMLIT_PORT: ${{ secrets.STREAMLIT_PORT || '8502' }}
      STREAMLIT_ADDRESS: ${{ secrets.STREAMLIT_ADDRESS || '0.0.0.0' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required envs
        run: |
          set -euo pipefail
          [ -n "${SSH_HOST:-}" ] && [ -n "${SSH_USER:-}" ] && [ -n "${DEPLOY_PATH:-}" ] || {
            echo "Missing SSH_HOST/SSH_USER/DEPLOY_PATH"; exit 1; }

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: SSH smoke test (publickey only)
        run: |
          set -euo pipefail
          ssh -vvv -o BatchMode=yes -o PreferredAuthentications=publickey \
            -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "echo 'SSH OK:' \$(whoami)@\$(hostname)"

      - name: Create remote directory
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -o PreferredAuthentications=publickey \
            -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$DEPLOY_PATH'"

      - name: Rsync source to server
        run: |
          set -euo pipefail
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.venv' \
            --exclude '__pycache__' \
            -e "ssh -o BatchMode=yes -o PreferredAuthentications=publickey -p $SSH_PORT" \
            ./ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"

      - name: Run remote deploy script
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -o PreferredAuthentications=publickey \
            -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
            "cd '$DEPLOY_PATH' && chmod +x scripts/deploy.sh && STREAMLIT_PORT='$STREAMLIT_PORT' STREAMLIT_ADDRESS='$STREAMLIT_ADDRESS' bash scripts/deploy.sh"
