name: Deploy to Server

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      STREAMLIT_PORT: ${{ secrets.STREAMLIT_PORT || '8502' }}
      STREAMLIT_ADDRESS: ${{ secrets.STREAMLIT_ADDRESS || '0.0.0.0' }}
      SSH_PRIVATE_KEY_B64: ${{ secrets.SSH_PRIVATE_KEY_B64 }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate required envs
        run: |
          set -euo pipefail
          [ -n "${SSH_HOST:-}" ] && [ -n "${SSH_USER:-}" ] && [ -n "${DEPLOY_PATH:-}" ] && [ -n "${SSH_PRIVATE_KEY_B64:-}" ] || {
            echo "Missing SSH_HOST/SSH_USER/DEPLOY_PATH/SSH_PRIVATE_KEY_B64"; exit 1; }

      - name: Prepare SSH key & agent
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          # Giải mã private key từ secret base64 và làm sạch CRLF nếu có
          echo "$SSH_PRIVATE_KEY_B64" | base64 -d > /tmp/gha_id_ed25519
          sed -i 's/\r$//' /tmp/gha_id_ed25519
          chmod 600 /tmp/gha_id_ed25519

          # Khởi tạo agent và nạp key
          eval "$(ssh-agent -s)"
          ssh-add /tmp/gha_id_ed25519

          # Thêm host vào known_hosts
          ssh-keyscan -H -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          # In fingerprint key đã nạp (để đối chiếu với server)
          echo "Agent keys fingerprint:"
          ssh-add -L | head -n1 | ssh-keygen -lf -

      - name: SSH smoke test (publickey only)
        run: |
          set -euo pipefail
          ssh -vvv -o BatchMode=yes -o IdentitiesOnly=yes -o PreferredAuthentications=publickey \
              -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "echo 'SSH OK: ' \$(whoami)@\$(hostname)"

      - name: Create remote directory
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -o IdentitiesOnly=yes -o PreferredAuthentications=publickey \
              -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "mkdir -p '$DEPLOY_PATH'"

      - name: Rsync source to server
        run: |
          set -euo pipefail
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.venv' \
            --exclude '__pycache__' \
            -e "ssh -o BatchMode=yes -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -p $SSH_PORT" \
            ./ "$SSH_USER@$SSH_HOST:$DEPLOY_PATH/"

      - name: Run remote deploy script
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -o IdentitiesOnly=yes -o PreferredAuthentications=publickey \
              -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" \
              "cd '$DEPLOY_PATH' && chmod +x scripts/deploy.sh && STREAMLIT_PORT='$STREAMLIT_PORT' STREAMLIT_ADDRESS='$STREAMLIT_ADDRESS' bash scripts/deploy.sh"
